kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.16
    commands:
      - go test -cover ./...

---
kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.16
    commands:
      - sh scripts/build.sh

  - name: publish
    image: plugins/ecr
    pull: if-not-exists
    settings:
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      repo: drone-runner-kube
      registry:
        from_secret: ecr_registry
      tags: ${DRONE_TAG}
    when:
      ref:
        - refs/tags/*

depends_on:
  - testing
  
trigger:
  ref:
    - refs/tags/**
